kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: okta
subjects:
- kind: Group
  name: "okta:SRE"
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: ""
